### ISSUE TITLE
Support for FIDO2: Web Authentication (WebAuthn)

### ISSUE THREAD

**Issue by hendrikhalkow** [onelogin/onelogin-python-aws-assume-role#57]
Hello, Could you please implement WebAuthn as a second authentication factor, please?

At the time of writing, you can already register a YubiKey via WebAuthn in the OneLogin web UI. However, this app doesn't support it [according to the source code](https://github.com/onelogin/onelogin-python-aws-assume-role/blob/61e1d6b84e30919e66a2f08391880bf1a263d233/src/aws_assume_role/aws_assume_role.py#L306).

Idea: Use the [FIDO2 library by Yubico](https://github.com/Yubico/python-fido2) to implement the [WebAuthn client authentication flow](https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/WebAuthn_Client_Authentication.html) into the CLI tool. I think the `get_saml_assertion_verifying` from the SDK function has to be tweaked as it only works with classical OTP tokens.

**Comment by pitbulk** [comment]
Yubikey token is a valid otp tolen that you can use in the toolkit, but providing it in the command line rather than integrated in the browser.

If you want to use the WebAuthn mechanism which requires a browser, rather that this aws-cli you can use the official aws cli v2
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html


See it in action here: https://www.youtube.com/watch?v=i44CtTOy8xY

**Comment by hendrikhalkow** [comment]
not required anymore. `aws sso login` does the job.
