### ISSUE TITLE
Please make a release!

### ISSUE THREAD

**Issue by ZsoltPath** [onelogin/onelogin-python-aws-assume-role#59]
There were 13 commits since the last release. Some just typos, but some very useful.

**Comment by cameron-cooper** [comment]
There needs to be another release added. The readme instructions are out of date with the files currently in the last major release.

**Comment by gyli** [comment]
Second this. For me, missing -c option is really annoying and I have to run the onelogin-aws-assume-role command in the folder containing the config files. However, in the latest README, it mentioned both of -c option and ~/.onelogin directory are available for putting config files, which is not true for v1.8.1.

My point is, currently GitHub README page is the primary documentation page of this project, so you might want to align your latest release with the README content.

**Comment by drewdavies** [comment]
I grabbed the latest release (1.8.1) via PyPi, added the configuration files to `~/.onelogin/` based on the README instructions, but kept getting exceptions because the functionality in @ZsoltPath's commit ([729fc0b](https://github.com/onelogin/onelogin-python-aws-assume-role/commit/729fc0b79ab5ed6988ba36256826fc9da1ef61bf)) from December 2020, isn't yet included.

**Comment by pitbulk** [comment]
1.9.0 was released!.
